import type { Course } from './types'

export const COURSES: Course[] = [
  // ─── MANICURE ───────────────────────────────────────────────
  {
    id: 'manicure-profesional',
    category: 'manicure',
    name: 'Manicure Profesional',
    slug: 'manicure-profesional',
    normal_price: 260000,
    offer_price: 240000,
    duration_text: '3 días intensivos de 10:00 a 18:00',
    deposit_amount: 60000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro de todas las técnicas'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Esmaltado Semipermanente', bullets: ['Preparación de las uñas', 'Nivelación y esmaltado', 'Degradé, francesa y encapsulado', 'Ojo de gato y efectos magnéticos'] },
      { title: 'Polygel', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Cristalería'] },
      { title: 'Acrílico', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Técnica reversa y flores 3D', 'Cristalería'] },
      { title: 'Soft gel', bullets: ['Preparación de las uñas', 'Aplicación de tips', 'Correcto limado', 'Esmaltado, francesa y degradé', 'Encapsulado y cristalería'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'manicure-integral',
    category: 'manicure',
    name: 'Manicure Integral',
    slug: 'manicure-integral',
    normal_price: 190000,
    offer_price: 180000,
    duration_text: '2 días intensivos de 10:00 a 18:00',
    deposit_amount: 40000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro de todas las técnicas'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Polygel', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Cristalería'] },
      { title: 'Esmaltado Semipermanente', bullets: ['Preparación de las uñas', 'Nivelación y esmaltado', 'Degradé, francesa y encapsulado', 'Ojo de gato y efectos magnéticos'] },
      { title: 'Acrílico', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Técnica reversa y flores 3D', 'Cristalería'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'manicure-esencial',
    category: 'manicure',
    name: 'Manicure Esencial',
    slug: 'manicure-esencial',
    normal_price: 195000,
    offer_price: 185000,
    duration_text: '2 días intensivos de 10:00 a 18:00',
    deposit_amount: 45000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro de todas las técnicas'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Polygel', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Cristalería'] },
      { title: 'Esmaltado Semipermanente', bullets: ['Preparación de las uñas', 'Nivelación y esmaltado', 'Degradé, francesa y encapsulado', 'Ojo de gato y efectos magnéticos'] },
      { title: 'Soft gel', bullets: ['Preparación de las uñas', 'Aplicación de tips', 'Correcto limado', 'Esmaltado, francesa y degradé', 'Encapsulado y cristalería'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'esmaltado-permanente-acrilico',
    category: 'manicure',
    name: 'Esmaltado Permanente + Acrílico',
    slug: 'esmaltado-permanente-acrilico',
    normal_price: 120000,
    offer_price: 110000,
    duration_text: '1 día intensivo de 10:00 a 18:00',
    deposit_amount: 30000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro de ambas técnicas'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Acrílico', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Técnica reversa y flores 3D', 'Cristalería'] },
      { title: 'Esmaltado Semipermanente', bullets: ['Preparación de las uñas', 'Nivelación y esmaltado', 'Degradé, francesa y encapsulado', 'Ojo de gato y efectos magnéticos'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'esmaltado-permanente-polygel',
    category: 'manicure',
    name: 'Esmaltado Permanente + Polygel',
    slug: 'esmaltado-permanente-polygel',
    normal_price: 120000,
    offer_price: 110000,
    duration_text: '1 día intensivo de 10:00 a 18:00',
    deposit_amount: 30000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro de ambas técnicas'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Polygel', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Cristalería'] },
      { title: 'Esmaltado Semipermanente', bullets: ['Preparación de las uñas', 'Nivelación y esmaltado', 'Degradé, francesa y encapsulado', 'Ojo de gato y efectos magnéticos'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'esmaltado-permanente-soft-gel',
    category: 'manicure',
    name: 'Esmaltado Permanente + Soft Gel',
    slug: 'esmaltado-permanente-soft-gel',
    normal_price: 120000,
    offer_price: 110000,
    duration_text: '1 día intensivo de 10:00 a 18:00',
    deposit_amount: 30000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro de ambas técnicas'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Soft gel', bullets: ['Preparación de las uñas', 'Aplicación de tips', 'Correcto limado', 'Esmaltado, francesa y degradé', 'Encapsulado y cristalería'] },
      { title: 'Esmaltado Semipermanente', bullets: ['Preparación de las uñas', 'Nivelación y esmaltado', 'Degradé, francesa y encapsulado', 'Ojo de gato y efectos magnéticos'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'soft-gel-inicial',
    category: 'manicure',
    name: 'Soft Gel Inicial',
    slug: 'soft-gel-inicial',
    normal_price: 100000,
    offer_price: 90000,
    duration_text: '1 día intensivo de 10:00 a 17:30',
    deposit_amount: 30000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Soft gel', bullets: ['Preparación de las uñas', 'Aplicación de tips', 'Correcto limado', 'Esmaltado, francesa y degradé', 'Encapsulado y cristalería'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'acrilico-inicial',
    category: 'manicure',
    name: 'Acrílico Inicial',
    slug: 'acrilico-inicial',
    normal_price: 100000,
    offer_price: 90000,
    duration_text: '1 día intensivo de 10:00 a 17:30',
    deposit_amount: 30000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Acrílico', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Técnica reversa y flores 3D', 'Cristalería'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'polygel-inicial',
    category: 'manicure',
    name: 'Polygel Inicial',
    slug: 'polygel-inicial',
    normal_price: 100000,
    offer_price: 90000,
    duration_text: '1 día intensivo de 10:00 a 17:30',
    deposit_amount: 30000,
    includes: ['Certificado', 'Materiales en clases', 'Manual impreso', 'Lista de proveedores', 'Descuentos en tiendas', 'Asesoría post curso', 'Snack', 'Retiro seguro'],
    temario: [
      { title: 'Manicure completa y torno', bullets: ['Anatomía y enfermedades', 'Uso de torno (técnica mixta)', 'Esterilización de materiales'] },
      { title: 'Polygel', bullets: ['Preparación de las uñas', 'Postura de moldes', 'Manejo y aplicación', 'Correcto limado', 'Encapsulado y baby boomer', 'Cristalería'] },
    ],
    active: true,
    created_at: '2024-01-01',
  },

  // ─── PESTAÑAS Y CEJAS ────────────────────────────────────────
  {
    id: 'integral-pestanas-cejas',
    category: 'pestanas_cejas',
    name: 'Integral Pestañas y Cejas',
    slug: 'integral-pestanas-cejas',
    normal_price: 285000,
    offer_price: 260000,
    duration_text: '3 días intensivos de 10:00 a 18:00',
    deposit_amount: 60000,
    includes: ['Certificado', 'Materiales profesionales en clases', 'Manual de apoyo impreso', 'Lista de insumos con descuento en tiendas', 'Asesoría post curso', 'Snack'],
    temario: [
      { title: 'Teoría y Bioseguridad', bullets: ['Preparación y sanitización', 'Contraindicaciones', 'Ficha técnica y consentimiento'] },
      { title: 'Extensión de Pestañas', bullets: ['Técnicas: clásica, volumen, rímel', 'Efectos: closed fans, máscara, f. tecnológicas', 'Diseño de mirada: ojo de gato, muñeca, ardilla'] },
      { title: 'Lash lifting y Técnica coreana', bullets: ['Tipos y curvaturas de bigudíes', 'Técnica de acople', 'Aplicación correcta', 'Tinte, nutrición y bótox', 'Técnica reversa'] },
      { title: 'Diseño de cejas perfectas', bullets: ['Visagismo (brow mapping)', 'Epilación con hilo y cera', 'Laminado (brow lamination)', 'Técnica ombré y pigmentación (henna y refectocil)'] },
      { title: 'Práctica avanzada', bullets: ['Direccionamiento y mapping', 'Uso y aplicación de adhesivo', 'Retoque y retiro', 'Correcto empalme'] },
    ],
    notes: 'Práctica full en modelos reales',
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'extension-cejas',
    category: 'pestanas_cejas',
    name: 'Extensión y Cejas',
    slug: 'extension-cejas',
    normal_price: 195000,
    offer_price: 185000,
    duration_text: '2 días intensivos de 10:00 a 18:00',
    deposit_amount: 55000,
    includes: ['Certificado', 'Materiales profesionales en clases', 'Manual de apoyo impreso', 'Lista de insumos con descuento en tiendas', 'Asesoría post curso', 'Snack'],
    temario: [
      { title: 'Teoría y Bioseguridad', bullets: ['Preparación y sanitización', 'Contraindicaciones', 'Ficha técnica y consentimiento'] },
      { title: 'Extensión de Pestañas', bullets: ['Técnicas: clásica, volumen, rímel', 'Efectos: closed fans, máscara, f. tecnológicas', 'Diseño de mirada: ojo de gato, muñeca, ardilla'] },
      { title: 'Diseño de cejas perfectas', bullets: ['Visagismo (brow mapping)', 'Epilación con hilo y cera', 'Laminado (brow lamination)', 'Técnica ombré y pigmentación (henna y refectocil)'] },
      { title: 'Práctica avanzada', bullets: ['Direccionamiento y mapping', 'Uso y aplicación de adhesivo', 'Retoque y retiro', 'Correcto empalme'] },
    ],
    notes: 'Práctica full en modelos reales',
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'extension-lifting-coreana',
    category: 'pestanas_cejas',
    name: 'Extensión y Lifting + Técnica Coreana',
    slug: 'extension-lifting-coreana',
    normal_price: 195000,
    offer_price: 185000,
    duration_text: '2 días intensivos de 10:00 a 18:00',
    deposit_amount: 55000,
    includes: ['Certificado', 'Materiales profesionales en clases', 'Manual de apoyo impreso', 'Lista de insumos con descuento en tiendas', 'Asesoría post curso', 'Snack'],
    temario: [
      { title: 'Teoría, anatomía y bioseguridad', bullets: ['Anatomía de las pestañas', 'Sanitización de materiales', 'Contraindicaciones', 'Ficha técnica y consentimiento'] },
      { title: 'Extensión de Pestañas', bullets: ['Técnicas: clásica, volumen, rímel', 'Efectos: closed fans, máscara, f. tecnológicas', 'Diseño de mirada: ojo de gato, muñeca, ardilla'] },
      { title: 'Lash lifting y Técnica coreana', bullets: ['Tipos y curvaturas de bigudíes', 'Técnica de acople', 'Aplicación correcta', 'Tinte, nutrición y bótox', 'Técnica reversa'] },
      { title: 'Práctica avanzada', bullets: ['Direccionamiento y mapping', 'Uso y aplicación de adhesivo', 'Retoque y retiro', 'Correcto empalme'] },
    ],
    notes: 'Práctica full en modelos reales',
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'extension-pestanas',
    category: 'pestanas_cejas',
    name: 'Extensión de Pestañas',
    slug: 'extension-pestanas',
    normal_price: 135000,
    offer_price: 125000,
    duration_text: '1 día intensivo de 10:00 a 18:00',
    deposit_amount: 55000,
    includes: ['Certificado', 'Materiales profesionales en clases', 'Manual de apoyo impreso', 'Lista de insumos con descuento en tiendas', 'Asesoría post curso', 'Snack'],
    temario: [
      { title: 'Teoría, anatomía y bioseguridad', bullets: ['Anatomía de las pestañas', 'Sanitización de materiales', 'Contraindicaciones', 'Ficha técnica y consentimiento'] },
      { title: 'Técnicas y efectos', bullets: ['Técnicas: clásica, volumen, rímel', 'Efectos: closed fans, máscara, f. tecnológicas'] },
      { title: 'Diseño de mirada', bullets: ['Personalización', 'Mapeo de estructuras comerciales', 'Efecto ojo de gato, muñeca y ardilla'] },
      { title: 'Práctica avanzada', bullets: ['Direccionamiento y mapping', 'Uso y aplicación de adhesivo', 'Retoque y retiro', 'Correcto empalme'] },
    ],
    notes: 'Práctica full en modelos reales y maniquí',
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'cejas-perfectas',
    category: 'pestanas_cejas',
    name: 'Cejas Perfectas',
    slug: 'cejas-perfectas',
    normal_price: 120000,
    offer_price: 110000,
    duration_text: '1 día intensivo de 10:00 a 17:30',
    deposit_amount: 55000,
    includes: ['Certificado', 'Materiales profesionales en clases', 'Manual de apoyo impreso', 'Lista de insumos con descuento en tiendas', 'Asesoría post curso', 'Snack'],
    temario: [
      { title: 'Teoría, anatomía y bioseguridad', bullets: ['Anatomía de las cejas', 'Bioseguridad', 'Marcas del mercado', 'Manejo de materiales profesionales'] },
      { title: 'Técnicas y efectos', bullets: ['Técnicas: clásica, volumen, rímel', 'Efectos: closed fans, máscara, f. tecnológicas'] },
      { title: 'Diseño de mirada', bullets: ['Personalización', 'Mapeo de estructuras comerciales', 'Efecto ojo de gato, muñeca y ardilla'] },
      { title: 'Práctica avanzada', bullets: ['Direccionamiento y mapping', 'Uso y aplicación de adhesivo', 'Retoque y retiro', 'Correcto empalme'] },
    ],
    notes: 'Práctica full en modelos reales y maniquí',
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'lifting-tecnica-coreana',
    category: 'pestanas_cejas',
    name: 'Lifting + Técnica Coreana',
    slug: 'lifting-tecnica-coreana',
    normal_price: 120000,
    offer_price: 110000,
    duration_text: '1 día intensivo de 10:00 a 17:30',
    deposit_amount: 30000,
    includes: ['Certificado', 'Materiales profesionales en clases', 'Manual de apoyo impreso', 'Lista de insumos con descuento en tiendas', 'Asesoría post curso', 'Snack'],
    temario: [
      { title: 'Teoría, anatomía y bioseguridad', bullets: ['Anatomía de las pestañas', 'Bioseguridad', 'Marcas del mercado', 'Manejo de materiales profesionales'] },
      { title: 'Lifting tradicional y coreano', bullets: ['Estudio profundo de las diferencias técnicas', 'Tipos de curvaturas', 'Elección correcta de bigudíes según el ojo'] },
      { title: 'Técnicas avanzadas y acabados', bullets: ['Técnica de acople perfecto', 'Protocolo de aplicación', 'Uso de tinte', 'Nutrición profunda y bótox', 'Técnica reversa de lifting'] },
    ],
    notes: 'Práctica full en modelos reales con productos profesionales',
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'cejas-lifting-coreana',
    category: 'pestanas_cejas',
    name: 'Cejas + Lifting Técnica Coreana',
    slug: 'cejas-lifting-coreana',
    normal_price: 195000,
    offer_price: 185000,
    duration_text: '2 días intensivos de 10:00 a 17:30',
    deposit_amount: 55000,
    includes: ['Certificado', 'Materiales profesionales en clases', 'Manual de apoyo impreso', 'Lista de insumos con descuento en tiendas', 'Asesoría post curso', 'Snack'],
    temario: [
      { title: 'Teoría, anatomía y bioseguridad', bullets: ['Anatomía de pestañas y cejas', 'Bioseguridad', 'Marcas del mercado', 'Manejo de materiales profesionales'] },
      { title: 'Lifting tradicional y coreano', bullets: ['Tipos y curvaturas de bigudíes', 'Técnica de acople', 'Aplicación correcta', 'Tinte, nutrición y bótox', 'Técnica reversa'] },
      { title: 'Cejas y Colorimetría', bullets: ['Visagismo (brow mapping)', 'Técnicas de visagismo', 'Perfilado y epilación con cera', 'Laminado (brow lamination)', 'Técnica ombré', 'Pigmentación con henna y refectocil'] },
    ],
    notes: 'Práctica full en modelos reales con productos profesionales',
    active: true,
    created_at: '2024-01-01',
  },
]

export function getCourseBySlug(slug: string): Course | undefined {
  return COURSES.find(c => c.slug === slug && c.active)
}

export function getCoursesByCategory(category: Course['category']): Course[] {
  return COURSES.filter(c => c.category === category && c.active)
}
